easy_admin:
  list:
    actions:
      - { name: 'edit', icon: 'pencil', label: '' }
      - { name: 'delete', icon: 'trash', label: '' }
  entities:
    User:
      class: App\Entity\User
    Project:
      class: App\Entity\Project
      form:
        fields:
          - { property: 'id' }
          - { property: 'name' }
          - { property: 'user' }
          - { property: 'consomation' }
          - { property: 'pvgis' }
          - { property: 'ninja' }
          - { property: 'csvProd' }
          - { property: 'finance' }

    Finance:
      class: App\Entity\Finance
    Consomation:
      class: App\Entity\Consomation 
    Pvgis:
      class: App\Entity\Pvgis     
    CsvProd:
      class: App\Entity\CsvProd 
    Ninja:
      class: App\Entity\Ninja    

