easy_admin:
  list:
    actions:
      - { name: 'edit', icon: 'pencil', label: '' }
      - { name: 'delete', icon: 'trash', label: '' }
  entities:
    User:
      class: App\Entity\User
    Project:
      class: App\Entity\Project
      form:
        fields:
          - 'id'
          - 'name'
          - 'adress'
          - 'description'
          - 'user'
          - 'pvwatt'
          - 'pvgis'
          - 'consomation'
    Finance:
      class: App\Entity\Finance
    Consomation:
      class: App\Entity\Consomation 
    Pvgis:
      class: App\Entity\Pvgis     

